project:
  type: book

book:
  title: "eLatim"
  author: "Lucas Consolin Dezotti"
  date: "3/11/2025"
  chapters:
  - index.qmd
  - ab.qmd
  - abeo.qmd
  - absum.qmd
  - accedo.qmd
  - accido.qmd
  - accipio.qmd
  - acer.qmd
  - acies.qmd
  - ad.qmd
  - addo.qmd
  - adduco.qmd
  - adeo.qmd
  - adeo2.qmd
  - adhibeo.qmd
  - adhuc.qmd
  - adsum.qmd
  - aduenio.qmd
  - aduersus.qmd
  - aduersus2.qmd
  - aduersus3.qmd
  - aduerto.qmd
  - aedes.qmd
  - aeger.qmd
  - aegre.qmd
  - aeque.qmd
  - aequor.qmd
  - aequus.qmd
  - aer.qmd
  - aes.qmd
  - aetas.qmd
  - aeternus.qmd
  - aether.qmd
  - aeuum.qmd
  - affero.qmd
  - afficio.qmd
  - ager.qmd
  - agito.qmd
  - agmen.qmd
  - ago.qmd
  - aio.qmd
  - albus.qmd
  - alienus.qmd
  - aliquando.qmd
  - aliquis.qmd
  - aliter.qmd
  - alius.qmd
  - alo.qmd
  - alter.qmd
  - altus.qmd
  - amicitia.qmd
  - amicus.qmd
  - amicus2.qmd
  - amitto.qmd
  - amnis.qmd
  - amo.qmd
  - amor.qmd
  - amplus.qmd
  - an.qmd
  - anima.qmd
  - animal.qmd
  - animus.qmd
  - annus.qmd
  - ante.qmd
  - antequam.qmd
  - antiquus.qmd
  - aperio.qmd
  - apio.qmd
  - appareo.qmd
  - appello.qmd
  - aptus.qmd
  - apud.qmd
  - aqua.qmd
  - ara.qmd
  - arbitror.qmd
  - arbor.qmd
  - ardeo.qmd
  - argentum.qmd
  - arma.qmd
  - ars.qmd
  - aruum.qmd
  - arx.qmd
  - ascendo.qmd
  - aspicio.qmd
  - astrum.qmd
  - at.qmd
  - atque.qmd
  - auctor.qmd
  - auctoritas.qmd
  - audax.qmd
  - audeo.qmd
  - audio.qmd
  - aufero.qmd
  - augeo.qmd
  - auis.qmd
  - aura.qmd
  - aureus.qmd
  - auris.qmd
  - aurum.qmd
  - aut.qmd
  - autem.qmd
  - auxilium.qmd
  - barbarus.qmd
  - beatus.qmd
  - bellum.qmd
  - bene.qmd
  - beneficium.qmd
  - beo.qmd
  - bonus.qmd
  - bos.qmd
  - breuis.qmd
  - breuiter.qmd
  - cado.qmd
  - caecus.qmd
  - caedes.qmd
  - caedo.qmd
  - caelestis.qmd
  - caelum.qmd
  - campus.qmd
  - candidus.qmd
  - canis.qmd
  - cano.qmd
  - capio.qmd
  - caput.qmd
  - careo.qmd
  - carmen.qmd
  - carus.qmd
  - castrum.qmd
  - castus.qmd
  - casus.qmd
  - caueo.qmd
  - causa.qmd
  - cedo.qmd
  - celebro.qmd
  - celer.qmd
  - celeris.qmd
  - celeriter.qmd
  - censeo.qmd
  - centum.qmd
  - cerno.qmd
  - certe.qmd
  - certo.qmd
  - certus.qmd
  - ceterum.qmd
  - ceterus.qmd
  - cibus.qmd
  - cieo.qmd
  - cingo.qmd
  - cinis.qmd
  - circa.qmd
  - citus.qmd
  - ciuis.qmd
  - ciuitas.qmd
  - clamor.qmd
  - clarus.qmd
  - classis.qmd
  - claudo.qmd
  - coepio.qmd
  - cogito.qmd
  - cognosco.qmd
  - cogo.qmd
  - cohors.qmd
  - colligo.qmd
  - colo.qmd
  - color.qmd
  - coma.qmd
  - comes.qmd
  - committo.qmd
  - communis.qmd
  - comparo.qmd
  - compono.qmd
  - concedo.qmd
  - condicio.qmd
  - condo.qmd
  - confero.qmd
  - conficio.qmd
  - confiteor.qmd
  - coniunx.qmd
  - conor.qmd
  - consequor.qmd
  - consilium.qmd
  - consisto.qmd
  - constituo.qmd
  - consto.qmd
  - consuetudo.qmd
  - consul.qmd
  - consulo.qmd
  - consumo.qmd
  - contemno.qmd
  - contineo.qmd
  - contingo.qmd
  - contra.qmd
  - conuenio.qmd
  - conuerto.qmd
  - conuiuium.qmd
  - copia.qmd
  - cor.qmd
  - cornu.qmd
  - corpus.qmd
  - corrumpo.qmd
  - credo.qmd
  - creo.qmd
  - cresco.qmd
  - crimen.qmd
  - culpa.qmd
  - cum.qmd
  - cunctus.qmd
  - cupido.qmd
  - cupio.qmd
  - cur.qmd
  - cura.qmd
  - curo.qmd
  - curro.qmd
  - currus.qmd
  - cursus.qmd
  - custos.qmd
  - damno.qmd
  - damnum.qmd
  - de.qmd
  - debeo.qmd
  - decem.qmd
  - decerno.qmd
  - decet.qmd
  - decus.qmd
  - deduco.qmd
  - defendo.qmd
  - defero.qmd
  - deficio.qmd
  - deinde.qmd
  - denique.qmd
  - descendo.qmd
  - desero.qmd
  - desidero.qmd
  - desino.qmd
  - desum.qmd
  - deus.qmd
  - dexter.qmd
  - dico.qmd
  - dies.qmd
  - differo.qmd
  - difficilis.qmd
  - dignitas.qmd
  - dignus.qmd
  - diligo.qmd
  - dimitto.qmd
  - discedo.qmd
  - disciplina.qmd
  - disco.qmd
  - diu.qmd
  - diuersus.qmd
  - diuerto.qmd
  - diues.qmd
  - diuido.qmd
  - diuitiae.qmd
  - diuus.qmd
  - do.qmd
  - doceo.qmd
  - doleo.qmd
  - dolor.qmd
  - dolus.qmd
  - dominus.qmd
  - domus.qmd
  - donec.qmd
  - dono.qmd
  - donum.qmd
  - dormio.qmd
  - dubito.qmd
  - dubius.qmd
  - duco.qmd
  - dulcis.qmd
  - dum.qmd
  - duo.qmd
  - durus.qmd
  - dux.qmd
  - ea.qmd
  - ecce.qmd
  - edico.qmd
  - edo.qmd
  - educo.qmd
  - efficio.qmd
  - effundo.qmd
  - ego.qmd
  - egredior.qmd
  - egregius.qmd
  - eligo.qmd
  - enim.qmd
  - eo.qmd
  - epistula.qmd
  - eques.qmd
  - equus.qmd
  - ergo.qmd
  - eripio.qmd
  - erro.qmd
  - error.qmd
  - et.qmd
  - etiam.qmd
  - ex.qmd
  - excipio.qmd
  - exemplum.qmd
  - exeo.qmd
  - exerceo.qmd
  - exercitus.qmd
  - exigo.qmd
  - exilium.qmd
  - existimo.qmd
  - experior.qmd
  - exspecto.qmd
  - extremus.qmd
  - fabula.qmd
  - facies.qmd
  - facilis.qmd
  - facinus.qmd
  - facio.qmd
  - factum.qmd
  - fallo.qmd
  - falsus.qmd
  - fama.qmd
  - fames.qmd
  - familia.qmd
  - fateor.qmd
  - fatum.qmd
  - fax.qmd
  - feliciter.qmd
  - felix.qmd
  - femina.qmd
  - fere.qmd
  - fero.qmd
  - ferrum.qmd
  - ferus.qmd
  - fessus.qmd
  - fidelis.qmd
  - fides.qmd
  - filia.qmd
  - fingo.qmd
  - finis.qmd
  - fio.qmd
  - flamma.qmd
  - fleo.qmd
  - flos.qmd
  - fluctus.qmd
  - flumen.qmd
  - fluo.qmd
  - foedus.qmd
  - fons.qmd
  - for.qmd
  - fore.qmd
  - forma.qmd
  - fors.qmd
  - fors2.qmd
  - fortis.qmd
  - fortuna.qmd
  - forum.qmd
  - frango.qmd
  - frater.qmd
  - frequens.qmd
  - frons.qmd
  - fructus.qmd
  - frumentum.qmd
  - fruor.qmd
  - frustra.qmd
  - fuga.qmd
  - fugio.qmd
  - fugo.qmd
  - fundo.qmd
  - funus.qmd
  - furor.qmd
  - gaudeo.qmd
  - gaudium.qmd
  - gens.qmd
  - genus.qmd
  - gero.qmd
  - gigno.qmd
  - gladius.qmd
  - gloria.qmd
  - gradus.qmd
  - gratia.qmd
  - gratus.qmd
  - grauis.qmd
  - habeo.qmd
  - haud.qmd
  - hic.qmd
  - hic2.qmd
  - hiems.qmd
  - hinc.qmd
  - homo.qmd
  - honestus.qmd
  - honor.qmd
  - hora.qmd
  - hortor.qmd
  - hospes.qmd
  - hostis.qmd
  - humanus.qmd
  - humus.qmd
  - iaceo.qmd
  - iacio.qmd
  - iam.qmd
  - ibi.qmd
  - ictus.qmd
  - idem.qmd
  - ideo.qmd
  - igitur.qmd
  - ignis.qmd
  - illa.qmd
  - ille.qmd
  - imago.qmd
  - imperator.qmd
  - imperium.qmd
  - impero.qmd
  - impetus.qmd
  - impleo.qmd
  - impono.qmd
  - in.qmd
  - incido.qmd
  - incipio.qmd
  - inde.qmd
  - indico.qmd
  - infero.qmd
  - inferus.qmd
  - ingenium.qmd
  - ingens.qmd
  - ingratus.qmd
  - ingredior.qmd
  - inimicus.qmd
  - initium.qmd
  - iniuria.qmd
  - inquam.qmd
  - instituo.qmd
  - insula.qmd
  - integer.qmd
  - intellego.qmd
  - intendo.qmd
  - inter.qmd
  - interficio.qmd
  - interim.qmd
  - interrogo.qmd
  - intersum.qmd
  - intra.qmd
  - intro.qmd
  - inuenio.qmd
  - inuidia.qmd
  - ipse.qmd
  - ira.qmd
  - irascor.qmd
  - is.qmd
  - iste.qmd
  - ita.qmd
  - itaque.qmd
  - item.qmd
  - iter.qmd
  - iterum.qmd
  - iubeo.qmd
  - iudex.qmd
  - iudicium.qmd
  - iudico.qmd
  - iugum.qmd
  - iungo.qmd
  - iuro.qmd
  - ius.qmd
  - iustus.qmd
  - iuuenis.qmd
  - iuuo.qmd
  - labor.qmd
  - laboro.qmd
  - lacrima.qmd
  - laedo.qmd
  - laetus.qmd
  - lapis.qmd
  - lateo.qmd
  - latus.qmd
  - latus2.qmd
  - laudo.qmd
  - laus.qmd
  - legatus.qmd
  - legio.qmd
  - lego.qmd
  - leuis.qmd
  - lex.qmd
  - liber.qmd
  - liber2.qmd
  - libertas.qmd
  - libet.qmd
  - libido.qmd
  - licet.qmd
  - limen.qmd
  - lingua.qmd
  - littera.qmd
  - litus.qmd
  - locus.qmd
  - longe.qmd
  - longus.qmd
  - loquor.qmd
  - lumen.qmd
  - luna.qmd
  - lux.qmd
  - maestus.qmd
  - magis.qmd
  - magister.qmd
  - magnitudo.qmd
  - magnus.qmd
  - maiores.qmd
  - male.qmd
  - malo.qmd
  - malus.qmd
  - maneo.qmd
  - manus.qmd
  - mare.qmd
  - maritus.qmd
  - mater.qmd
  - materia.qmd
  - medius.qmd
  - membrum.qmd
  - memini.qmd
  - memoria.qmd
  - mens.qmd
  - mensa.qmd
  - mereo.qmd
  - metuo.qmd
  - metus.qmd
  - meus.qmd
  - miles.qmd
  - mille.qmd
  - miror.qmd
  - misceo.qmd
  - miser.qmd
  - mitto.qmd
  - modo.qmd
  - modus.qmd
  - moenia.qmd
  - mollis.qmd
  - moneo.qmd
  - mons.qmd
  - mora.qmd
  - morbus.qmd
  - morior.qmd
  - moror.qmd
  - mors.qmd
  - mortalis.qmd
  - mos.qmd
  - moueo.qmd
  - mox.qmd
  - mulier.qmd
  - multitudo.qmd
  - multus.qmd
  - mundus.qmd
  - mundus2.qmd
  - munus.qmd
  - murus.qmd
  - muto.qmd
  - nam.qmd
  - narro.qmd
  - nascor.qmd
  - natura.qmd
  - natus.qmd
  - nauis.qmd
  - ne.qmd
  - ne2.qmd
  - nec.qmd
  - necesse.qmd
  - necessitas.qmd
  - nefas.qmd
  - nego.qmd
  - negotium.qmd
  - nemo.qmd
  - nemus.qmd
  - neque.qmd
  - nescio.qmd
  - niger.qmd
  - nihil.qmd
  - nimis.qmd
  - nimius.qmd
  - nisi.qmd
  - nobilis.qmd
  - noceo.qmd
  - nolo.qmd
  - nomen.qmd
  - non.qmd
  - nondum.qmd
  - nos.qmd
  - nosco.qmd
  - noster.qmd
  - notus.qmd
  - nouus.qmd
  - nox.qmd
  - nudus.qmd
  - nullus.qmd
  - num.qmd
  - numen.qmd
  - numerus.qmd
  - numquam.qmd
  - nunc.qmd
  - nuntius.qmd
  - ob.qmd
  - occido.qmd
  - occupo.qmd
  - occurro.qmd
  - oculus.qmd
  - odi.qmd
  - odium.qmd
  - offero.qmd
  - officium.qmd
  - olim.qmd
  - omnis.qmd
  - onus.qmd
  - opera.qmd
  - oportet.qmd
  - oppidum.qmd
  - ops.qmd
  - opto.qmd
  - opus.qmd
  - oratio.qmd
  - orbis.qmd
  - ordo.qmd
  - orior.qmd
  - oro.qmd
  - os.qmd
  - os2.qmd
  - ostendo.qmd
  - otium.qmd
  - paene.qmd
  - par.qmd
  - parco.qmd
  - parens.qmd
  - pareo.qmd
  - pario.qmd
  - paro.qmd
  - pars.qmd
  - parum.qmd
  - paruus.qmd
  - pateo.qmd
  - pater.qmd
  - patior.qmd
  - patria.qmd
  - pauci.qmd
  - paullus.qmd
  - paulo.qmd
  - pauper.qmd
  - pax.qmd
  - pecco.qmd
  - pectus.qmd
  - pecunia.qmd
  - pecus.qmd
  - pello.qmd
  - pendo.qmd
  - per.qmd
  - perdo.qmd
  - pereo.qmd
  - pergo.qmd
  - periculum.qmd
  - permitto.qmd
  - perpetuus.qmd
  - pertineo.qmd
  - peruenio.qmd
  - pes.qmd
  - peto.qmd
  - pietas.qmd
  - pius.qmd
  - placeo.qmd
  - plebs.qmd
  - plenus.qmd
  - plerique.qmd
  - plerumque.qmd
  - plerusque.qmd
  - poena.qmd
  - poeta.qmd
  - pondus.qmd
  - pono.qmd
  - pontus.qmd
  - populus.qmd
  - porta.qmd
  - porto.qmd
  - posco.qmd
  - possum.qmd
  - post.qmd
  - postea.qmd
  - posterus.qmd
  - postquam.qmd
  - potens.qmd
  - potestas.qmd
  - potis.qmd
  - praebeo.qmd
  - praeceptum.qmd
  - praecipio.qmd
  - praeda.qmd
  - praemium.qmd
  - praesens.qmd
  - praesidium.qmd
  - praesto.qmd
  - praeter.qmd
  - praeterea.qmd
  - praetor.qmd
  - precor.qmd
  - premo.qmd
  - pretium.qmd
  - prex.qmd
  - primum.qmd
  - primus.qmd
  - princeps.qmd
  - principium.qmd
  - prior.qmd
  - priuatus.qmd
  - priuo.qmd
  - prius.qmd
  - pro.qmd
  - probo.qmd
  - procedo.qmd
  - procul.qmd
  - prodo.qmd
  - proelium.qmd
  - proficiscor.qmd
  - prohibeo.qmd
  - promitto.qmd
  - prope.qmd
  - prope2.qmd
  - propero.qmd
  - propono.qmd
  - proprius.qmd
  - propter.qmd
  - prosum.qmd
  - protinus.qmd
  - prouincia.qmd
  - publicus.qmd
  - pudor.qmd
  - puella.qmd
  - puer.qmd
  - pugna.qmd
  - pugno.qmd
  - pulcher.qmd
  - puto.qmd
  - qua.qmd
  - qua2.qmd
  - quaero.qmd
  - qualis.qmd
  - quamquam.qmd
  - quamuis.qmd
  - quando.qmd
  - quantum.qmd
  - quantus.qmd
  - quare.qmd
  - quasi.qmd
  - quattuor.qmd
  - que.qmd
  - quemadmodum.qmd
  - queror.qmd
  - qui.qmd
  - quia.qmd
  - quicumque.qmd
  - quidam.qmd
  - quidem.qmd
  - quiesco.qmd
  - quin.qmd
  - quippe.qmd
  - quis.qmd
  - quisquam.qmd
  - quisquis.qmd
  - quomodo.qmd
  - quondam.qmd
  - quoniam.qmd
  - quotiens.qmd
  - rapio.qmd
  - rarus.qmd
  - ratio.qmd
  - recedo.qmd
  - recens.qmd
  - recipio.qmd
  - rectus.qmd
  - reddo.qmd
  - redeo.qmd
  - refero.qmd
  - regio.qmd
  - regius.qmd
  - regnum.qmd
  - rego.qmd
  - relinquo.qmd
  - reliquus.qmd
  - reor.qmd
  - reperio.qmd
  - repeto.qmd
  - res.qmd
  - respicio.qmd
  - respondeo.qmd
  - retineo.qmd
  - reuerto.qmd
  - reuoco.qmd
  - reus.qmd
  - rex.qmd
  - rideo.qmd
  - ripa.qmd
  - rogo.qmd
  - rumpo.qmd
  - rursus.qmd
  - rus.qmd
  - sacer.qmd
  - sacerdos.qmd
  - saeculum.qmd
  - saepe.qmd
  - saeuus.qmd
  - salus.qmd
  - sancio.qmd
  - sancitus.qmd
  - sanguis.qmd
  - sanus.qmd
  - sapiens.qmd
  - sapiens2.qmd
  - sapientia.qmd
  - sapio.qmd
  - satis.qmd
  - saxum.qmd
  - scelus.qmd
  - scientia.qmd
  - scilicet.qmd
  - scio.qmd
  - scribo.qmd
  - secundus.qmd
  - securus.qmd
  - sed.qmd
  - sedeo.qmd
  - sedes.qmd
  - semel.qmd
  - semper.qmd
  - senatus.qmd
  - senex.qmd
  - sensus.qmd
  - sententia.qmd
  - sentio.qmd
  - sepulcrum.qmd
  - sequor.qmd
  - sermo.qmd
  - seruio.qmd
  - seruo.qmd
  - seruus.qmd
  - seu.qmd
  - si.qmd
  - sic.qmd
  - sicut.qmd
  - sidus.qmd
  - signum.qmd
  - silua.qmd
  - similis.qmd
  - simul.qmd
  - sine.qmd
  - singuli.qmd
  - sino.qmd
  - sinus.qmd
  - siue.qmd
  - siue2.qmd
  - socius.qmd
  - socius2.qmd
  - sol.qmd
  - soleo.qmd
  - solum.qmd
  - soluo.qmd
  - solus.qmd
  - somnus.qmd
  - sono.qmd
  - soror.qmd
  - sors.qmd
  - spargo.qmd
  - spatium.qmd
  - species.qmd
  - specto.qmd
  - spero.qmd
  - spes.qmd
  - spiritus.qmd
  - statim.qmd
  - statuo.qmd
  - stella.qmd
  - sto.qmd
  - studeo.qmd
  - studium.qmd
  - sub.qmd
  - subeo.qmd
  - subito.qmd
  - sui.qmd
  - sum.qmd
  - sumo.qmd
  - super.qmd
  - super2.qmd
  - superbus.qmd
  - superi.qmd
  - supero.qmd
  - supersum.qmd
  - superus.qmd
  - supplicium.qmd
  - supra.qmd
  - supra2.qmd
  - surgo.qmd
  - suscipio.qmd
  - sustineo.qmd
  - suus.qmd
  - taceo.qmd
  - talis.qmd
  - tam.qmd
  - tamen.qmd
  - tamquam.qmd
  - tandem.qmd
  - tango.qmd
  - tantum.qmd
  - tantus.qmd
  - tardus.qmd
  - tectum.qmd
  - tego.qmd
  - tellus.qmd
  - telum.qmd
  - tempestas.qmd
  - templum.qmd
  - tempto.qmd
  - tempus.qmd
  - tendo.qmd
  - tenebrae.qmd
  - teneo.qmd
  - tener.qmd
  - tergum.qmd
  - terra.qmd
  - terreo.qmd
  - tertius.qmd
  - testis.qmd
  - timeo.qmd
  - timor.qmd
  - tollo.qmd
  - tot.qmd
  - totus.qmd
  - trado.qmd
  - traho.qmd
  - transeo.qmd
  - tres.qmd
  - tribunus.qmd
  - tristis.qmd
  - tu.qmd
  - tueo.qmd
  - tueor.qmd
  - tuitus.qmd
  - tum.qmd
  - turba.qmd
  - turbo.qmd
  - turpis.qmd
  - tuus.qmd
  - uaco.qmd
  - uacuus.qmd
  - uagus.qmd
  - ualeo.qmd
  - ualidus.qmd
  - uanus.qmd
  - uarius.qmd
  - uates.qmd
  - ubi.qmd
  - ue.qmd
  - ueho.qmd
  - uel.qmd
  - uelut.qmd
  - uenio.qmd
  - uentus.qmd
  - uerbum.qmd
  - uere.qmd
  - uereor.qmd
  - uero.qmd
  - uerto.qmd
  - uerus.qmd
  - uester.qmd
  - uestigium.qmd
  - uestis.qmd
  - ueto.qmd
  - uetus.qmd
  - uia.qmd
  - uicinus.qmd
  - uictor.qmd
  - uictoria.qmd
  - uideo.qmd
  - uinco.qmd
  - uinculum.qmd
  - uinum.qmd
  - uir.qmd
  - uirgo.qmd
  - uirtus.qmd
  - uis.qmd
  - uita.qmd
  - uitium.qmd
  - uito.qmd
  - uiuo.qmd
  - uix.qmd
  - ullus.qmd
  - ultimus.qmd
  - ultra.qmd
  - ultra2.qmd
  - umbra.qmd
  - umquam.qmd
  - unda.qmd
  - unde.qmd
  - undique.qmd
  - unus.qmd
  - uoco.qmd
  - uolo.qmd
  - uolucer.qmd
  - uolucris.qmd
  - uoluntas.qmd
  - uoluptas.qmd
  - uos.qmd
  - uotum.qmd
  - uox.qmd
  - urbs.qmd
  - usque.qmd
  - usus.qmd
  - ut.qmd
  - uterque.qmd
  - utilis.qmd
  - utor.qmd
  - utrum.qmd
  - uulgo.qmd
  - uulgus.qmd
  - uulnus.qmd
  - uultus.qmd
  - uxor.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4





